name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 取得程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 登入 Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=tonyhsueh630/practice-app:${GITHUB_REF_NAME}
          docker build -t $IMAGE_NAME .

      # 4. Push image
      - name: Push Docker image
        run: |
          IMAGE_NAME=tonyhsueh630/practice-app:${GITHUB_REF_NAME}
          docker push $IMAGE_NAME
